Repository wecode-bootcamp-korea/23-1st-RushOur-backend, pull requests merged in 2021-08, with the labels that each got.

#1 models.py 작성
  .gitignore
  banners/__init__.py
  banners/admin.py
  banners/apps.py
  banners/migrations/0001_initial.py
  banners/migrations/__init__.py
  banners/models.py
  banners/tests.py
  banners/views.py
  carts/__init__.py
  carts/admin.py
  carts/apps.py
  carts/migrations/0001_initial.py
  carts/migrations/__init__.py
  carts/models.py
  carts/tests.py
  carts/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  rushour/settings.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
  wishlists/__init__.py
  wishlists/admin.py
  wishlists/apps.py
  wishlists/migrations/0001_initial.py
  wishlists/migrations/__init__.py
  wishlists/models.py
  wishlists/tests.py
  wishlists/views.py
Labels: Status: Accepted

#2 feature/user
  carts/urls.py
  carts/view.py
  carts/views.py
  requirements.txt
  rushour/urls.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#4 [23기 한상웅] Refactor:오류 메세지 변경
  users/migrations/0002_auto_20210806_0348.py
  users/migrations/0003_auto_20210806_0554.py
  users/models.py
  users/views.py
Labels: Status: 리뷰 요청

#3 [23기 최민] Modify: 컴프리핸션 사용, url 엔드포인트 수정
  products/urls.py
  products/views.py
  rushour/urls.py
Labels: Status: Accepted

#5 [23기 최민] Add: 상품리스트 기능 추가, 필터링 기능 구현
  .gitignore
  products/urls.py
  products/views.py
  rushour/urls.py
Labels: Status: Accepted

#6 [23기 최민] Modify: 수정사항 반영 완료, conflict 해결
  products/urls.py
  products/views.py
Labels: Status: 수정 요청

#8 [23기 최민] Add: 배너 이미지 기능 추가
  banners/urls.py
  banners/views.py
  rushour/urls.py
Labels: Status: Accepted

#9 [23기 최민] Add: 상품리스트에 limit, offset 기능 추가
  products/views.py
Labels: Status: Accepted

#10 [23기 최민] Add: 장바구니 생성, Read 기능 추가
  carts/urls.py
  carts/view.py
  carts/views.py
  rushour/urls.py
Labels: Status: Accepted

#7 [23기 한상웅] Refactor:리뷰반영(컨벤션)
  rushour/urls.py
  wishlists/urls.py
  wishlists/views.py
Labels: Status: 리뷰 요청

#11 [23기 최민] Add: 장바구니 수량 변경 기능 추가, 삭제 기능 추가
  carts/urls.py
  carts/views.py
Labels: Status: 리뷰 요청

#12 [23기 최민] Add: 장바구니 옵션별 생성 기능 추가
  carts/views.py
  products/views.py
Labels: Status: 리뷰 요청
